services:
  mlflow:
    build: .
    restart: always
    ports:
      - "5000:5000"
    env_file: .env
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      --default-artifact-root gs://mlflow-demo-artifacts
      --host 0.0.0.0
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgres
